<?php
declare(strict_types=1);


namespace tight_coupling\tests;

use PHPUnit\Framework\TestCase;
use tight_coupling\Builder;

class Data_Exporter_Test extends TestCase
{
    
    public function setUp(): void
    {
        require __DIR__ . '/../Builder.php';
        require __DIR__ . '/../Data_Exporter.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_export() {
        $builder = new class implements Builder {
            public function build( array $products ) {
                // TODO: Implement build() method.
            }
        };
        
        $data_exporter = new \tight_coupling\Data_Exporter();
        
        $data_exporter->export( [], $builder );
        $this->expectNotToPerformAssertions();
    }
}
