<?php

use PHPUnit\Framework\TestCase;

class Add_Test extends TestCase
{


  public function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub
    require __DIR__ . '/../example.php';
  }


  public function test_add_function()
  {
    $this->assertEquals(4, add(2, 2));
  }
}
