<?php
declare( strict_types=1 );


class Product_Test extends \PHPUnit\Framework\TestCase {

	private $product;
	public function setUp(): void {
		require_once __DIR__ . '/../product.php';
		parent::setUp(); // TODO: Change the autogenerated stub
	}
	
	public function test_can_get_inventory() {
		$this->product = new Product();
		$this->assertEquals( 0, $this->product->getInventory() );
		
		$this->product->addStock( 5 );
		$this->assertEquals( 5, $this->product->getInventory() );
	}
	
}
