<?php
declare( strict_types=1 );

class Slug_Test extends  \PHPUnit\Framework\TestCase {

	public function setUp(): void {
		require_once __DIR__ . '/../slug.php';
		parent::setUp(); // TODO: Change the autogenerated stub
	}
	
	public function test_slugify() {
		$this->assertEquals( 'hello-world', slugify( 'Hello World' ) );
		$this->assertEquals( 'hello-world', slugify( 'Hello      World' ) );
		$this->assertEquals( 'hello-world', slugify( '     Hello World' ) );
		$this->assertEquals( 'hello-world', slugify( 'Hello World     ' ) );
	}
	
	public function test_slugify_with_punctuation_at_the_end() {
		$this->assertEquals( 'hello-world', slugify( 'Hello World!' ) );
	}
}
