<?php
declare(strict_types=1);


namespace tests;

class Redirect_Test extends \PHPUnit\Framework\TestCase
{

    function setUp(): void
    {
        require_once __DIR__ . '/../redirect.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function test_should_redirect()
    {
        $path = 'foo';

        $redirects = [
            'foo' => 'bar'
        ];

        $this->assertTrue(should_redirect($path, $redirects));
        $this->assertFalse(should_redirect('baz', $redirects));
        
        $this->assertTrue(should_redirect( 'foo/bar', $redirects));
    }
    
    function test_get_top_level_path() {
        $this->assertEquals( 'foo', get_top_level_path( 'foo/bar' ) );
    }
}
