<?php
declare(strict_types=1);


namespace tests;

use Project\Redirect\RedirectVO;


class RedirectVO_Test extends \PHPUnit\Framework\TestCase
{

    public function setUp(): void
    {
        require_once __DIR__ . '/../vendor/autoload.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_can_construct()
    {
        $redirect = new RedirectVO('foo', 'bar');
        $this->assertInstanceOf( RedirectVO::class, $redirect);

        $this->expectException(\InvalidArgumentException::class);
        $redirect = new RedirectVO('', 'bar');
        $redirect = new RedirectVO('foo', '');
        $redirect = new RedirectVO('https://www.linkedin.com', 'bar');
    }

    public function test_equals()
    {
        $redirect = new RedirectVO('foo', 'bar');
        $this->assertTrue($redirect->equals(new RedirectVO('foo', 'bar')));
        $this->assertFalse($redirect->equals(new RedirectVO('foo', 'baz')));
        $this->assertFalse($redirect->equals(new RedirectVO('baz', 'bar')));
    }

}
