<?php
declare(strict_types=1);


namespace tests;

class Redirect_Test extends \PHPUnit\Framework\TestCase
{

    function setUp(): void
    {
        require __DIR__ . '/../redirect.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function test_should_redirect()
    {
        $path = 'foo';

        $redirects = [
            'foo' => 'bar'
        ];

        $this->assertTrue(should_redirect($path, $redirects));
        $this->assertFalse(should_redirect('baz', $redirects));
    }
}
