<?php
declare(strict_types=1);


namespace tests;

class Redirect_Test extends \PHPUnit\Framework\TestCase
{

    function setUp(): void
    {
        require_once __DIR__ . '/../redirect.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    function test_get_top_level_path() {
        $this->assertEquals( 'foo', get_top_level_path( 'foo/bar' ) );
    }
}
